
parameters:
    toolbar.bundle.controller.class: BackBee\Bundle\ToolbarBundle\Controller\ConfigController
    toolbar.bundle.plugin.manager.class: BackBee\Bundle\ToolbarBundle\Plugin\PluginManager

    error.base_folder: %bbapp.base.dir%/../toolbar-bundle/Resources/layouts/error/
    error.404: 'error.twig'
    error.500: 'error.twig'
    error.default: 'error.twig'

services:
    plugin.manager:
        class: %toolbar.bundle.plugin.manager.class%
        arguments: [@service_container]

    toolbar.controller:
        class: %toolbar.bundle.controller.class%
        arguments: [@bundle.toolbar.config, @plugin.manager, @routing]
