core:
    ApplicationManager:
        appPath: $resources-baseurl$/toolbar/src/tb/apps
        active: main
        route: ""
        applications:

            main:
                label: Main
                config:
                    mainRoute: appMain/index

            content:
                label: Edition du contenu
                config: []

            bundle:
                label: Bundle
                config:
                    mainRoute: bundle/index

            page:
                label: Page
                config:
                    mainRoute: page/index

            contribution:
                label: Contribution
                config:
                    mainRoute: contribution/index

            user:
                label: User
                config:
                    mainRoute: user/index
                scope:
                    global:
                        open: user.showCurrent

wrapper_toolbar_id: 'bb5-ui'

default_url: 'content/contribution/edit'

component:

    logger:
        level: 8
        mode: 'devel'

    exceptions-viewer:
        show: true
        showInConsole: true

    medialibrary:
        available_media:
          - {title: 'Image', type: 'Media/Image', ico: 'fa fa-picture'}

    translator:
        base: '$resources-baseurl$/toolbar/src/tb/i18n/'
        default_locale: 'en_US'
        locales:
            en_US: 'EN'
            fr_FR: 'FR'

    medialibrary:
        available_media:
            - { 'type': 'Media/Image', 'title': 'Image' }


unclickable_contents:
    contents:
        - 'Element/Text'
        - 'Element/Attachment'
        - 'Element/Date'
        - 'Element/File'
        - 'Element/Image'
        - 'Element/Keyword'
        - 'Element/Link'
        - 'Element/Select'
