core:
    ApplicationManager:
        appPath: resources/toolbar/src/tb/apps
        active: main
        route: ""
        applications:

            main:
                label: Main
                config:
                    mainRoute: appMain/index

            layout:
                label: Layout
                config:
                    mainRoute: appLayout/home

            content:
                label: Edition du contenu
                config: []

            bundle:
                label: Bundle
                config:
                    mainRoute: bundle/index

            page:
                label: Page
                config:
                    mainRoute: page/index

            contribution:
                label: Contribution
                config:
                    mainRoute: contribution/index

component:
    logger: []
